### ISSUE TITLE
FEATURE REQUEST: Custom CSS theme

### ISSUE THREAD

**Issue by LIGMATV** [hibbitts-design/docsify-this#1]
Can we customize the style just directly from docsify-this?

Example:

https:/&sol;docsify-this.net/?basePath=https:/&sol;raw.githubusercontent.com/hibbitts-design/docsify-this-one-page-article/main&homepage=home.md#**&custom-css=https:/&sol;cdn.jsdelivr.net/npm/docsify/lib/themes/vue.css**

And it will response...

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify/lib/themes/vue.css">
```

Or even for the dark user

https:/&sol;docsify-this.net/?basePath=https:/&sol;raw.githubusercontent.com/hibbitts-design/docsify-this-one-page-article/main&homepage=home.md#&custom-css=https:/&sol;cdn.jsdelivr.net/npm/docsify/lib/themes/vue.css
**&custom-css-dark=https:/&sol;cdn.jsdelivr.net/gh/sushantrahate/docsify-darkly-theme/css/darkly.min.css**

And it will response...

```html
<link rel="stylesheet" media="(prefers-color-scheme: dark)" href="https://cdn.jsdelivr.net/gh/sushantrahate/docsify-darkly-theme/css/darkly.min.css">
```

**Comment by paulhibbitts** [comment]
Thanks for your question @LIGMATV. For this more advanced functionality I would suggest forking Docsify-This and then you can experiment and see what might be possible. A lot of fine-tuning has been done based on Docsify-Themeable so switching to the default vue.css stylesheet will likely cause a number of issues as well. BTW, dark mode is currently support by using the `dark-mode` parameter - system OS settings will automatically set the light/dark theme.

**Comment by LIGMATV** [comment]
> Thanks for your feature request @LIGMATV. For this more advanced customization I would suggest forking Docsify-This and then you can experiment and see what might be possible. A lot of fine-tuning has been done based on Docsify-Themeable so switching to the default vue.css stylesheet will likely cause a number of issues as well. BTW, dark mode is currently supported by using the `dark-mode` parameter - system OS settings will automatically set the light/dark theme as provided by Docsify-Themeable.
> 
> I love what you are doing with your own Docsify themes and plugins!

I really agree. I already make my own fork and change the theme, but it so much different. I like how them work in Docsify Themeable ecosystem.

**Comment by BenutzerEinsZweiDrei** [comment]
While i truly enjoyed the provided designs, i wanted to make some customisations while not hosting my own instance. This caused some complications because i had to understand how docsify loads pages and how to style with no access to the index and instead staying in the markdown.

I found a good solution

- With adding `&coverpage=README.md&onlyCover=true` to the url you use the coverpage.
- With adding `&link-color=none&coverpage-color=none&link-color-dark-mode=none&coverpage-color-dark-mode=none` you remove some colors

Add a theme from themeable for example in md

```
<!-- Theme: Simple Dark -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsify-themeable@0/dist/css/theme-simple-dark.css">
```

Afterwards implement custom css with <style> tag id md
For example

```
<style>
/* Cover
============================================================================= */
:root {
    /* Colors */
    --cover-color                                      : ;
    --cover-margin                                     : 0 auto;
    --cover-max-width                                  : 40em;
    --cover-text-align                                 : center;

    /* Background */
    --cover-background-blend-mode                      : ;
    --cover-background-color                           : var(--base-background-color);
    --cover-background-mask-color                      : var(--base-background-color);
    --cover-background-mask-opacity                    : 0.8;
    --cover-background-mask-visibility                 : ;
    --cover-background-position                        : center center;
    --cover-background-repeat                          : no-repeat;
    --cover-background-size                            : cover;

    /* Border */
    --cover-border-inset                               : 0;
    --cover-border-color                               : grey;
    --cover-border-width                               : 7px;
    
    /* Heading */
    --cover-heading-color                              : #C4A484;
}
</style>
```

Additional info
- <script> tags are executed after the site is loaded. Thats why hooks dont work.
- waiting for dom to load is not possible so you have to use plugin hooks.
- it is not possible to implement plugins in <script> tags
- it would be possible to directly style content in <script> tag with `document.querySelector`
- it is possible to implement code in svg files. idk if this even works with new embed function of docsify.
- more would even be possible with vuejs
- normally you can style with `![color](#f0f0f0)`
